//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace RotorSync
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<channels>();
                db.CreateTable<config>();
                db.CreateTable<frequencymap>();
                db.CreateTable<HDHR>();
            }
        }
    }
    public partial class channels
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        public String callsign { get; set; }
        
        [NotNull]
        public Int64 realchannel { get; set; }
        
        public Int64? virtualchannel { get; set; }
        
        public String network { get; set; }
        
        public Double? distance { get; set; }
        
        [NotNull]
        public Int64 azimuth { get; set; }
        
    }
    
    public partial class config
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public Int64 sensitivity { get; set; }
        
        public String HDHRdeviceID { get; set; }
        
        public Int64? rotorTimeout { get; set; }
        
        public Int64? rotorAzimuth { get; set; }
        
        public String rotorCOMPort { get; set; }
        
    }
    
    public partial class frequencymap
    {
        [PrimaryKey, AutoIncrement]
        public Int64 channel { get; set; }
        
        [NotNull]
        public Int64 frequency { get; set; }
        
    }
    
    public partial class HDHR
    {
        [PrimaryKey, AutoIncrement]
        public Int64 Id { get; set; }
        
        [NotNull]
        public String deviceID { get; set; }
        
        [NotNull]
        public String ip { get; set; }
        
    }
    
}
