//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RotorSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RotorSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -- Script Date: 1/30/2017 3:51 PM  - ErikEJ.SqlCeScripting version 3.5.2.64
        ///-- Database information:
        ///-- Database: C:\Code\RotorSync\RotorSync\RSDatabase.db
        ///-- ServerVersion: 3.14.2
        ///-- DatabaseSize: 24 KB
        ///-- Created: 12/22/2016 9:18 PM
        ///
        ///-- User Table information:
        ///-- Number of tables: 4
        ///-- channels: -1 row(s)
        ///-- config: -1 row(s)
        ///-- frequencymap: -1 row(s)
        ///-- HDHR: -1 row(s)
        ///
        ///SELECT 1;
        ///PRAGMA foreign_keys=OFF;
        ///
        ///INSERT INTO [HDHR] ([Id],[deviceID],[ip]) VALUES (
        ///1,&apos;1050A596&apos;,&apos;192.168.15.108&apos;) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RSData {
            get {
                return ResourceManager.GetString("RSData", resourceCulture);
            }
        }
    }
}
